name: FXStreet Scraper Every 30 Minutes

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *" # každých 30 minut
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/upload-artifact@v2.3.1

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run scraper
        run: python scraper_fxstreet_playwright.py

      - name: Upload output
        uses: actions/upload-artifact@v2.3.1
        with:
          name: sentiment-data
          path: sentiment_data.json
